"""Quarantine is replay-only, causal, and never releases capital or creates fills."""

import json
from copy import deepcopy
from dataclasses import replace
from unittest.mock import patch

import pytest
from test_replay import START, Synthetic, config, row
from test_replay_integration import store, web_case  # noqa: F401
from test_replay_rejections import candle

from crypto_bot.replay import stale
from crypto_bot.replay.clock import at
from crypto_bot.replay.config import ConfigValidationError, input_config, validate
from crypto_bot.replay.engine import ReplayEngine, Variant
from crypto_bot.replay.exporter import payload
from crypto_bot.replay.models import ReplayStore
from crypto_bot.trading.domain import D


def variant(policy=stale.QUARANTINE, exit_policy="baseline_v1"):
    return Variant(
        config(variants=[dict(exit_policy=exit_policy)])["variants"][0], START, policy
    )


def open_front(v):
    v.signals([row() | dict(symbol="FRONTUSDT")], {"FRONTUSDT"}, START)
    v.execute_signals({"FRONTUSDT": {START: candle()}}, START, False)
    return v.ledger.portfolio.positions()[0]


def lose_front(v, now=START + 3600000):
    v.signals([row() | dict(symbol="ETHUSDT")], {"ETHUSDT"}, now)
    v.execute_signals({"ETHUSDT": {now: candle(now)}}, now, False)


def test_policy_default_validation_and_old_config_round_trip():
    c = config()
    assert c["stale_position_policy"] == stale.STRICT
    c.pop("stale_position_policy")
    assert input_config(c)["stale_position_policy"] == stale.STRICT
    for policy in stale.POLICIES:
        raw = input_config(c) | dict(stale_position_policy=policy)
        assert input_config(validate(raw)) == raw
    with pytest.raises(ConfigValidationError) as caught:
        validate(input_config(c) | dict(stale_position_policy="force_close"))
    assert caught.value.errors[0]["field"] == "stale_position_policy"


@pytest.mark.parametrize("policy,opens", [(stale.STRICT, 1), (stale.QUARANTINE, 2)])
def test_strict_blocks_and_research_continues_with_front_quarantined(policy, opens):
    v = variant(policy)
    front = open_front(v)
    cash = v.ledger.account.cash_balance
    cost = front.notional + front.entry_fee
    lose_front(v)
    assert len(v.ledger.portfolio.positions()) == opens
    assert front.status == "OPEN"  # Production ledger semantics untouched.
    report = v.trade(front, START + 7200000)
    assert report["status"] == "OPEN_STALE"
    assert report["quarantined"] == (policy == stale.QUARANTINE)
    assert report["first_stale_time"] == at(START + 3600000).isoformat() + "Z"
    assert report["last_valid_mark_time"] == at(START).isoformat() + "Z"
    assert report["last_valid_mark_price"] == "100.000000000000"
    assert D(report["capital_locked_by_stale_positions"]) == cost
    assert D(report["exposure_locked_by_stale_positions"]) >= cost
    assert v.ledger.account.cash_balance <= cash
    assert not v.closed
    assert v.blocked["other"] == (policy == stale.STRICT)


@pytest.mark.parametrize("mark", [80, 100, 150])
def test_stale_gain_never_increases_buying_power_and_loss_never_frees_exposure(mark):
    v = variant()
    front = open_front(v)
    v.mark({"FRONTUSDT": D(mark)}, START + 60000)
    before = v.ledger.account.cash_balance
    v.fresh_positions(set(), START + 3600000)
    report = v.ledger.portfolio.view()
    risk = v.decision_view()
    market = front.quantity * front.current_price
    cost = front.notional + front.entry_fee
    assert risk.equity == before + min(market, cost)
    assert risk.exposure == max(market, cost)
    assert report.equity == before + market
    assert risk.available_cash == report.available_cash == before
    assert len(risk.positions) == 1
    assert risk.equity <= report.equity
    assert risk.daily_pnl <= report.daily_pnl
    assert risk.exposure >= report.exposure
    assert v.ledger.account.cash_balance == before


def test_quarantined_position_still_uses_position_limit_and_unchanged_risk_manager():
    v = variant()
    v.settings = replace(v.settings, max_open_positions=1)
    v.risk.settings = v.settings
    open_front(v)
    lose_front(v)
    assert len(v.ledger.portfolio.positions()) == 1
    assert v.blocked_reasons["max open positions reached"] == 1


def test_no_symbol_action_or_retroactive_fill_and_resume_on_fresh_current_data():
    v = variant()
    front = open_front(v)
    now = START + 3600000
    # A SELL could have been generated by a closed 1h context, but cannot execute
    # for an unpriced position. Future candles must not count as fresh now.
    signal = v.strategy.evaluate(
        v.contexts([row() | dict(symbol="FRONTUSDT", total_score=40)], set(), now)[0][
            0
        ],
        True,
    )
    v.pending = [(signal, row())]
    v.execute_signals(
        {"FRONTUSDT": {now + 3600000: candle(now + 3600000, open=90)}}, now, False
    )
    assert stale.state(front)["quarantined"]
    assert len(v.execution.fills) == 1 and not v.closed
    assert v.events[-1]["event"] == "STALE_ACTION_SKIPPED"
    assert front.current_price == D(100)
    assert v.trade(front, now + 3600000)["exit_time"] is None
    resumed = now + 3600000
    v.pending = []
    v.execute_signals(
        {"FRONTUSDT": {resumed: candle(resumed, open=110)}}, resumed, False
    )
    assert not stale.state(front)["stale"] and not stale.state(front)["quarantined"]
    assert stale.state(front)["resumed_after_stale"]
    assert stale.state(front)["stale_duration_seconds"] == 3600
    assert front.current_price == D(110)
    assert len(v.execution.fills) == 1  # Unquarantine is a mark, not a fill.
    # The current completed bar can trigger the original stop; no absent bar is replayed.
    v.bar(
        "FRONTUSDT",
        candle(resumed, open=110, high=111, low=97, close=110),
        resumed + 60000,
        True,
    )
    assert len(v.closed) == 1
    assert v.closed[0]["exit_time"] == at(resumed + 60000).isoformat() + "Z"
    assert v.closed[0]["exit_reason"] == "ORIGINAL_STOP"
    assert v.closed[0]["exit_price"] != "100.000000000000"


@pytest.mark.parametrize(
    "policy",
    [
        "baseline_v1",
        "fixed_tp",
        "r_tp",
        "break_even",
        "trailing_pct",
        "trailing_r",
        "profit_lock",
    ],
)
def test_every_exit_policy_is_unchanged_in_research_without_missing_data(policy):
    results = []
    for mode in stale.POLICIES:
        v = variant(mode, policy)
        open_front(v)
        v.bar("FRONTUSDT", candle(high=104, low=97), START + 60000, True)
        results.append((v.execution.fills, v.ledger.account.cash_balance))
    assert results[0] == results[1]


def test_stale_checkpoint_preserves_last_mark_and_duration():
    v = variant()
    open_front(v)
    lose_front(v)
    snapshot = deepcopy(v.checkpoint())
    resumed = variant()
    resumed.ledger.restore(json.loads(json.dumps(snapshot["ledger"], default=str)))
    front = next(
        p for p in resumed.ledger.portfolio.positions() if p.symbol == "FRONTUSDT"
    )
    assert resumed.trade(front, START + 7200000)["stale_duration_seconds"] == 3600
    assert resumed.trade(front, START + 7200000)["status"] == "OPEN_STALE"
    resumed.fresh_positions({"FRONTUSDT", "ETHUSDT"}, START + 10800000)
    assert stale.state(front)["stale_duration_seconds"] == 7200
    assert stale.state(front)["resumed_after_stale"]


class MissingAfter(Synthetic):
    def minutes(self, symbol, start, end, interval="1m"):
        if symbol == "BTCUSDT" and start >= START + 6 * 3600000:
            return {}
        return super().minutes(symbol, start, end, interval)


def test_end_of_run_stale_results_export_and_no_forced_exit(tmp_path):
    db = ReplayStore(tmp_path / "replay.db")
    run = db.create(config(stale_position_policy=stale.QUARANTINE))
    # Real pipeline with deterministic reference features and fixed score solely
    # for the fixture; production feature/score code is not edited.
    features = row()["features"] | dict(
        quote_volume=100000000,
        spread=0.02,
        trend="bullish",
        atr_pct=2.5,
        momentum=5,
        range_position=0.9,
    )
    with patch("crypto_bot.replay.engine.features", return_value=features):
        ReplayEngine(db, MissingAfter()).run(run)
    result = db.get(run)
    metrics = result["variants"][0]["summary"]["metrics"]
    assert metrics["stale_position_count"] == 1
    assert metrics["stale_symbols"] == ["BTCUSDT"]
    assert not metrics["valuation_complete"] and not metrics["ranking_eligible"]
    assert metrics["stale_warning"] == stale.WARNING
    assert result["metadata"]["stale_position_policy"] == stale.QUARANTINE
    trades, _ = db.data(run)
    assert sum(t["status"] == "OPEN_STALE" for t in trades) == 1
    for compact in (False, True):
        exported = payload(db, run, compact=compact)
        assert any(t["status"] == "OPEN_STALE" for t in exported["open_positions"])
        assert exported["summary"]["stale_warning"] == stale.WARNING
    assert not metrics["blocked_entry_categories"].get("missing_portfolio_marks")


def test_comparison_warns_and_excludes_stale_result_from_ranking(request):
    client, db, _ = request.getfixturevalue("web_case")
    runs = []
    for affected in (False, True):
        run = db.create(config())
        db.complete(
            run,
            [
                dict(
                    metrics=dict(
                        stale_data_affected=affected,
                        stale_position_count=int(affected),
                        return_pct=99 if affected else 1,
                        blocked_entries={},
                    ),
                    breakdowns={},
                )
            ],
            {},
        )
        runs.append(run)
    response = client.get(
        "/api/replay/compare", query_string=[("selection", f"{r}:0") for r in runs]
    )
    assert response.status_code == 200
    data = response.json
    assert data["stale_warning"] == stale.WARNING
    assert data["variants"][0]["ranking_eligible"]
    assert not data["variants"][1]["ranking_eligible"]
    assert data["variants"][1]["summary"]["return_pct"] == 99


def test_research_stale_prefix_independent_of_future_data_return(tmp_path):
    class ReturnsLater(MissingAfter):
        def minutes(self, symbol, start, end, interval="1m"):
            if start >= START + 24 * 3600000:
                return Synthetic.minutes(self, symbol, start, end, interval)
            return super().minutes(symbol, start, end, interval)

    results = []
    f = row()["features"] | dict(
        quote_volume=100000000,
        spread=0.02,
        trend="bullish",
        atr_pct=2.5,
        momentum=5,
        range_position=0.9,
    )
    for i, provider in enumerate((MissingAfter(), ReturnsLater())):
        db = ReplayStore(tmp_path / str(i) / "replay.db")
        run = db.create(config(stale_position_policy=stale.QUARANTINE))
        with patch("crypto_bot.replay.engine.features", return_value=f):
            ReplayEngine(db, provider).run(run)
        with db.connection() as sql:
            events = [
                json.loads(r[0])
                for r in sql.execute("SELECT data FROM replay_audit_events ORDER BY id")
            ]
        cutoff = at(START + 24 * 3600000).isoformat() + "Z"
        _, curve = db.data(run)
        results.append(
            (
                [e for e in events if e["timestamp"] < cutoff],
                [r for r in curve if r["time"] < START + 24 * 3600000],
            )
        )
    assert results[0] == results[1]
    assert any(e["event"] == "POSITION_STALE" for e in results[0][0])
