"""paper ledger and operational status"""

import sqlalchemy as sa
from alembic import op

revision = "0002_paper"
down_revision = "0001_scanner"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "paper_account",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column("quote_asset", sa.String(length=20), nullable=False),
        sa.Column(
            "initial_balance",
            sa.Numeric(precision=30, scale=12).with_variant(sa.Text(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "cash_balance",
            sa.Numeric(precision=30, scale=12).with_variant(sa.Text(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "reserved_cash",
            sa.Numeric(precision=30, scale=12).with_variant(sa.Text(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "realized_pnl",
            sa.Numeric(precision=30, scale=12).with_variant(sa.Text(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "fees_paid",
            sa.Numeric(precision=30, scale=12).with_variant(sa.Text(), "sqlite"),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("day", sa.String(length=10), nullable=False),
        sa.Column(
            "day_start_equity",
            sa.Numeric(precision=30, scale=12).with_variant(sa.Text(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "peak_equity",
            sa.Numeric(precision=30, scale=12).with_variant(sa.Text(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "max_drawdown",
            sa.Numeric(precision=30, scale=12).with_variant(sa.Text(), "sqlite"),
            nullable=False,
        ),
        sa.Column("configuration", sa.JSON(), nullable=False),
        sa.Column("lease_owner", sa.String(length=50), nullable=True),
        sa.Column("lease_until", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "paper_portfolio_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column(
            "total_equity",
            sa.Numeric(precision=30, scale=12).with_variant(sa.Text(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "cash_balance",
            sa.Numeric(precision=30, scale=12).with_variant(sa.Text(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "reserved_cash",
            sa.Numeric(precision=30, scale=12).with_variant(sa.Text(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "available_cash",
            sa.Numeric(precision=30, scale=12).with_variant(sa.Text(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "realized_pnl",
            sa.Numeric(precision=30, scale=12).with_variant(sa.Text(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "unrealized_pnl",
            sa.Numeric(precision=30, scale=12).with_variant(sa.Text(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "fees_paid",
            sa.Numeric(precision=30, scale=12).with_variant(sa.Text(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "exposure",
            sa.Numeric(precision=30, scale=12).with_variant(sa.Text(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "daily_pnl",
            sa.Numeric(precision=30, scale=12).with_variant(sa.Text(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "max_drawdown",
            sa.Numeric(precision=30, scale=12).with_variant(sa.Text(), "sqlite"),
            nullable=False,
        ),
        sa.Column("open_positions", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_paper_portfolio_snapshots_timestamp"),
        "paper_portfolio_snapshots",
        ["timestamp"],
        unique=False,
    )
    op.create_table(
        "paper_processed_snapshots",
        sa.Column("snapshot_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["snapshots.id"],
        ),
        sa.PrimaryKeyConstraint("snapshot_id"),
    )
    op.create_table(
        "service_status",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("type", sa.String(length=12), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("version", sa.String(length=20), nullable=False),
        sa.Column("git_commit", sa.String(length=50), nullable=True),
        sa.Column("git_branch", sa.String(length=100), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("last_heartbeat", sa.DateTime(), nullable=True),
        sa.Column("last_success", sa.DateTime(), nullable=True),
        sa.Column("last_error_at", sa.DateTime(), nullable=True),
        sa.Column("last_error_message", sa.String(length=300), nullable=True),
        sa.Column("restart_count", sa.Integer(), nullable=False),
        sa.Column("owner", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "strategy_signals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("snapshot_id", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("symbol", sa.String(length=40), nullable=False),
        sa.Column("action", sa.String(length=8), nullable=False),
        sa.Column(
            "signal_strength",
            sa.Numeric(precision=30, scale=12).with_variant(sa.Text(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "entry_reference",
            sa.Numeric(precision=30, scale=12).with_variant(sa.Text(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "stop_reference",
            sa.Numeric(precision=30, scale=12).with_variant(sa.Text(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "take_profit_price",
            sa.Numeric(precision=30, scale=12).with_variant(sa.Text(), "sqlite"),
            nullable=True,
        ),
        sa.Column("strategy_name", sa.String(length=80), nullable=False),
        sa.Column("reasons", sa.JSON(), nullable=False),
        sa.Column("configuration", sa.JSON(), nullable=False),
        sa.Column("exit_reason", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["snapshots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_strategy_signals_timestamp"),
        "strategy_signals",
        ["timestamp"],
        unique=False,
    )
    op.create_table(
        "system_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("component", sa.String(length=50), nullable=False),
        sa.Column("level", sa.String(length=12), nullable=False),
        sa.Column("message", sa.String(length=300), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_system_events_timestamp"), "system_events", ["timestamp"], unique=False
    )
    op.create_table(
        "risk_decisions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("signal_id", sa.Integer(), nullable=False),
        sa.Column("approved", sa.Boolean(), nullable=False),
        sa.Column(
            "risk_amount",
            sa.Numeric(precision=30, scale=12).with_variant(sa.Text(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "position_notional",
            sa.Numeric(precision=30, scale=12).with_variant(sa.Text(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "quantity",
            sa.Numeric(precision=30, scale=12).with_variant(sa.Text(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "stop_distance_pct",
            sa.Numeric(precision=30, scale=12).with_variant(sa.Text(), "sqlite"),
            nullable=False,
        ),
        sa.Column("reasons", sa.JSON(), nullable=False),
        sa.Column("portfolio", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["signal_id"],
            ["strategy_signals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("signal_id"),
    )
    op.create_table(
        "paper_orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("signal_id", sa.Integer(), nullable=False),
        sa.Column("risk_id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=40), nullable=False),
        sa.Column("side", sa.String(length=4), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column(
            "quantity",
            sa.Numeric(precision=30, scale=12).with_variant(sa.Text(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "reference_price",
            sa.Numeric(precision=30, scale=12).with_variant(sa.Text(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "reserved_amount",
            sa.Numeric(precision=30, scale=12).with_variant(sa.Text(), "sqlite"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["risk_id"],
            ["risk_decisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"],
            ["strategy_signals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("signal_id"),
    )
    op.create_table(
        "paper_positions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=40), nullable=False),
        sa.Column("side", sa.String(length=4), nullable=False),
        sa.Column(
            "entry_price",
            sa.Numeric(precision=30, scale=12).with_variant(sa.Text(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "quantity",
            sa.Numeric(precision=30, scale=12).with_variant(sa.Text(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "notional",
            sa.Numeric(precision=30, scale=12).with_variant(sa.Text(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "stop_price",
            sa.Numeric(precision=30, scale=12).with_variant(sa.Text(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "take_profit_price",
            sa.Numeric(precision=30, scale=12).with_variant(sa.Text(), "sqlite"),
            nullable=True,
        ),
        sa.Column("opened_at", sa.DateTime(), nullable=False),
        sa.Column(
            "current_price",
            sa.Numeric(precision=30, scale=12).with_variant(sa.Text(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "entry_fee",
            sa.Numeric(precision=30, scale=12).with_variant(sa.Text(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "exit_fee",
            sa.Numeric(precision=30, scale=12).with_variant(sa.Text(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "unrealized_pnl",
            sa.Numeric(precision=30, scale=12).with_variant(sa.Text(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "realized_pnl",
            sa.Numeric(precision=30, scale=12).with_variant(sa.Text(), "sqlite"),
            nullable=False,
        ),
        sa.Column("strategy_name", sa.String(length=80), nullable=False),
        sa.Column("signal_id", sa.Integer(), nullable=False),
        sa.Column("entry_order_id", sa.Integer(), nullable=False),
        sa.Column("exit_order_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=8), nullable=False),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.Column(
            "exit_price",
            sa.Numeric(precision=30, scale=12).with_variant(sa.Text(), "sqlite"),
            nullable=True,
        ),
        sa.Column("exit_reason", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(
            ["entry_order_id"],
            ["paper_orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["exit_order_id"],
            ["paper_orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"],
            ["strategy_signals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_paper_positions_symbol_status",
        "paper_positions",
        ["symbol", "status"],
        unique=False,
    )
    op.create_table(
        "paper_fills",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("position_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column(
            "price",
            sa.Numeric(precision=30, scale=12).with_variant(sa.Text(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "quantity",
            sa.Numeric(precision=30, scale=12).with_variant(sa.Text(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "notional",
            sa.Numeric(precision=30, scale=12).with_variant(sa.Text(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "fee",
            sa.Numeric(precision=30, scale=12).with_variant(sa.Text(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "slippage",
            sa.Numeric(precision=30, scale=12).with_variant(sa.Text(), "sqlite"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["paper_orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["paper_positions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("paper_fills")
    op.drop_index("ix_paper_positions_symbol_status", table_name="paper_positions")
    op.drop_table("paper_positions")
    op.drop_table("paper_orders")
    op.drop_table("risk_decisions")
    op.drop_index(op.f("ix_system_events_timestamp"), table_name="system_events")
    op.drop_table("system_events")
    op.drop_index(op.f("ix_strategy_signals_timestamp"), table_name="strategy_signals")
    op.drop_table("strategy_signals")
    op.drop_table("service_status")
    op.drop_table("paper_processed_snapshots")
    op.drop_index(
        op.f("ix_paper_portfolio_snapshots_timestamp"),
        table_name="paper_portfolio_snapshots",
    )
    op.drop_table("paper_portfolio_snapshots")
    op.drop_table("paper_account")
    # ### end Alembic commands ###
