from typing import Protocol


class ExecutionService(Protocol):
    def place_order(self, signal_id: int, risk_id: int, now): ...
    def cancel_order(self, order_id: int, now): ...
    def get_order(self, order_id: int): ...
    def get_positions(self): ...
